"use client";

import { useState } from "react";
// Use the Beer type generated by Prisma
import type { Beer } from "@prisma/client"; // Adjust the import path as necessary
import { useRouter } from "next/navigation"; // Import useRouter for navigation
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
// Define props for the component
interface BeerListProps {
  initialBeers: Beer[];
}

export default function BeerList({ initialBeers }: BeerListProps) {
  const [beers, setBeers] = useState<Beer[]>(initialBeers);
  const router = useRouter(); // Initialize the router
  const [showAddForm, setShowAddForm] = useState(false);
  const [newBeer, setNewBeer] = useState({
    name: '',
    type: '',
    region: '',
    alcoholContent: '',
  });

  const toggleBeerTested = async (beerId: string) => {
    // Find the current state of the beer to determine the new state
    const beerToToggle = beers.find(beer => beer.id === beerId);
    if (!beerToToggle) return; // Should not happen, but good practice

    const newIsTested = !beerToToggle.isTested;

    // Optimistically update the UI
    setBeers(prev => prev.map(beer =>
      beer.id === beerId
        ? { ...beer, isTested: newIsTested }
        : beer
    ));

    // Persist the change to the database after updating the UI
    try {
      const response = await fetch(`/api/beers/${beerId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ isTested: newIsTested }),
      });

      if (!response.ok) {
        // Revert the state if the API call fails
        console.error('Failed to update beer status:', await response.text());
        setBeers(prev => prev.map(beer =>
          beer.id === beerId
            ? { ...beer, isTested: !newIsTested } // Revert to original state
            : beer
        ));
        // Optionally: Show an error message to the user
      }


      
    } catch (error) {
      console.error('Error updating beer status:', error);
      // Revert the state on network error etc.
      setBeers(prev => prev.map(beer =>
        beer.id === beerId
          ? { ...beer, isTested: !newIsTested } // Revert to original state
          : beer
      ));
      // Optionally: Show an error message to the user
    }

    router.refresh(); // Refresh the page to reflect the changes
  };

  const handleAddBeer = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
      const response = await fetch('/api/beers', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(newBeer),
      });

      if (!response.ok) {
        throw new Error('Failed to add beer');
      }

      const addedBeer = await response.json();
      setBeers(prev => [...prev, addedBeer]);
      setNewBeer({ name: '', type: '', region: '', alcoholContent: '' });
      setShowAddForm(false);
      router.refresh();
    } catch (error) {
      console.error('Error adding beer:', error);
      // Optionally: Show an error message to the user
    }
  };

  const handleDeleteBeer = async (beerId: string) => {
    try {
      const response = await fetch(`/api/beers/${beerId}`, {
        method: 'DELETE',
      });

      if (!response.ok) {
        throw new Error('Failed to delete beer');
      }

      setBeers(prev => prev.filter(beer => beer.id !== beerId));
      router.refresh();
    } catch (error) {
      console.error('Error deleting beer:', error);
      // Optionally: Show an error message to the user
    }
  };

  const testedCount = beers.filter(beer => beer.isTested).length;
  const progressPercentage = beers.length > 0 ? (testedCount / beers.length) * 100 : 0;

  return (
    <>
      {/* Progress Bar and Count */}
      <div className="relative w-full h-2.5 bg-[#f5e6c9] rounded-full overflow-hidden mb-2">
        <div 
          className="absolute left-0 top-0 h-full bg-[#e6b800] transition-all duration-300 ease-in-out"
          style={{ width: `${progressPercentage}%` }}
        />
      </div>
      <p className="text-[#8B4513] mb-8">
        {testedCount} of {beers.length} beers tasted ({Math.round(progressPercentage)}%)
      </p>

      {/* Add Beer Button */}
      <button
        onClick={() => setShowAddForm(!showAddForm)}
        className="mb-6 px-4 py-2 bg-[#daa520] text-white rounded-lg hover:bg-[#c99510] transition-colors"
      >
        {showAddForm ? 'Cancel' : 'Add New Beer'}
      </button>

      {/* Add Beer Form */}
      {showAddForm && (
        <form onSubmit={handleAddBeer} className="mb-8 space-y-4 p-6 bg-[#f8f8f8] rounded-lg border border-[#daa520]/20">
          <div>
            <input
              type="text"
              placeholder="Beer Name"
              value={newBeer.name}
              onChange={(e) => setNewBeer(prev => ({ ...prev, name: e.target.value }))}
              className="w-full p-2 border border-[#daa520]/20 rounded-md"
              required
            />
          </div>
          <div>
            <input
              type="text"
              placeholder="Beer Type"
              value={newBeer.type}
              onChange={(e) => setNewBeer(prev => ({ ...prev, type: e.target.value }))}
              className="w-full p-2 border border-[#daa520]/20 rounded-md"
              required
            />
          </div>
          <div>
            <input
              type="text"
              placeholder="Region"
              value={newBeer.region}
              onChange={(e) => setNewBeer(prev => ({ ...prev, region: e.target.value }))}
              className="w-full p-2 border border-[#daa520]/20 rounded-md"
              required
            />
          </div>
          <div>
            <input
              type="number"
              step="0.1"
              placeholder="Alcohol Content (%)"
              value={newBeer.alcoholContent}
              onChange={(e) => setNewBeer(prev => ({ ...prev, alcoholContent: e.target.value }))}
              className="w-full p-2 border border-[#daa520]/20 rounded-md"
              required
            />
          </div>
          <button
            type="submit"
            className="w-full py-2 bg-[#daa520] text-white rounded-lg hover:bg-[#c99510] transition-colors"
          >
            Add Beer
          </button>
        </form>
      )}

      {/* Beer List */}
      <div className="space-y-4">
        {beers.map(beer => (
          <div 
            key={beer.id} 
            className={`
              p-4 rounded-lg border transition-all duration-200 group
              ${beer.isTested 
                ? 'bg-white border-[#e6b800] shadow-lg shadow-[#e6b800]/10' 
                : 'bg-white hover:bg-[#fbfbfb] hover:border-[#daa520] hover:shadow-md'}
            `}
          >
            <div className="flex items-center space-x-4">
              <div 
                className={`
                  h-6 w-6 rounded-md border-2 cursor-pointer transition-all duration-200 flex items-center justify-center
                  ${beer.isTested 
                    ? 'bg-[#daa520] border-[#daa520] text-white' 
                    : 'border-[#8B4513]/30 hover:border-[#daa520]'}
                `}
                onClick={() => toggleBeerTested(beer.id)}
              >
                {beer.isTested && (
                  <svg className="w-4 h-4" viewBox="0 0 24 24">
                    <path
                      fill="currentColor"
                      d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"
                    />
                  </svg>
                )}
              </div>
              <div className="flex-1">
                <div className="flex justify-between items-start relative">
                  <h2 className="text-xl font-roboto font-semibold text-[#a86823]">{beer.name}</h2>
                  <Dialog>
                    <DialogTrigger asChild>
                      <button
                        className="text-red-500 hover:text-red-700 p-1 absolute -right-1 opacity-0 group-hover:opacity-100 transition-opacity duration-200"
                      >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                      </button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>Delete Beer</DialogTitle>
                        <DialogDescription>
                          Are you sure you want to delete &ldquo;{beer.name}&rdquo;? This action cannot be undone.
                        </DialogDescription>
                      </DialogHeader>
                      <DialogFooter>
                        <Button variant="outline" onClick={() => handleDeleteBeer(beer.id)}>
                          Delete
                        </Button>
                      </DialogFooter>
                    </DialogContent>
                  </Dialog>
                </div>
                <div className="flex flex-wrap gap-2 mt-2">
                  <span className="text-sm px-2.5 py-1 rounded-md bg-[#f8f8f8] text-[#8B4513] border border-[#daa520]/20">
                    {beer.type}
                  </span>
                  <span className="text-sm px-2.5 py-1 rounded-md bg-[#f8f8f8] text-[#8B4513] border border-[#daa520]/20">
                    {beer.region}
                  </span>
                  <span className="text-sm px-2.5 py-1 rounded-md bg-[#fafafa] text-[#8B4513] border border-[#daa520]/20">
                    {beer.alcoholContent}% ABV
                  </span>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
