// data.ts
export interface Beer {
    id: number;
    name: string;
    type: string;
    brewery: string;
    region: string;
    alcoholContent: number;
    isTested: boolean;
  }
  
  export const germanBeers: Beer[] = [
    {
      id: 1,
      name: "Weihenstephaner Hefe Weissbier",
      type: "Hefeweizen",
      brewery: "Bayerische Staatsbrauerei Weihenstephan",
      region: "Bavaria",
      alcoholContent: 5.4,
      isTested: false,
    },
    {
      id: 2,
      name: "Bitburger Premium Pils",
      type: "Pilsner",
      brewery: "Bitburger Brauerei",
      region: "Rhineland-Palatinate",
      alcoholContent: 4.8,
      isTested: false,
    },
    {
      id: 3,
      name: "Paulaner Hefe-Weißbier",
      type: "Hefeweizen",
      brewery: "Paulaner Brauerei",
      region: "Bavaria",
      alcoholContent: 5.5,
      isTested: true,
   },
    {
      id: 4,
      name: "Augustiner Helles",
      type: "Helles Lager",
      brewery: "Augustiner-Bräu Wagner KG",
      region: "Bavaria",
      alcoholContent: 5.2,
      isTested: false,
    },
    {
      id: 5,
      name: "Krombacher Pils",
      type: "Pilsner",
      brewery: "Krombacher Brauerei",
      region: "North Rhine-Westphalia",
      alcoholContent: 4.8,
      isTested: true,
    },
    {
      id: 6,
      name: "Franziskaner Hefe-Weißbier",
      type: "Hefeweizen",
      brewery: "Spaten-Franziskaner-Bräu GmbH",
      region: "Bavaria",
      alcoholContent: 5.0,
      isTested: false,
    },
    {
      id: 7,
      name: "Beck’s",
      type: "Pilsner",
      brewery: "Brauerei Beck & Co.",
      region: "Bremen",
      alcoholContent: 4.9,
      isTested: true,
    },
    {
      id: 8,
      name: "Warsteiner Premium Verum",
      type: "Pilsner",
      brewery: "Warsteiner Brauerei",
      region: "North Rhine-Westphalia",
      alcoholContent: 4.8,
      isTested: false,
    },
    {
      id: 9,
      name: "Hacker-Pschorr Münchner Gold",
      type: "Helles Lager",
      brewery: "Hacker-Pschorr Bräu GmbH",
      region: "Bavaria",
      alcoholContent: 5.5,
      isTested: false,
    },
    {
      id: 10,
      name: "Spaten Oktoberfest",
      type: "Märzen",
      brewery: "Spaten-Franziskaner-Bräu GmbH",
      region: "Bavaria",
      alcoholContent: 5.9,
      isTested: false,
    },
    {
      id: 11,
      name: "Paulaner Salvator",
      type: "Doppelbock",
      brewery: "Paulaner Brauerei",
      region: "Bavaria",
      alcoholContent: 7.9,
      isTested: true,
    },
    {
      id: 12,
      name: "Aecht Schlenkerla Rauchbier Märzen",
      type: "Rauchbier",
      brewery: "Brauerei Heller Bamberg",
      region: "Bavaria",
      alcoholContent: 5.1,
      isTested: false,
    },
    {
      id: 13,
      name: "Erdinger Weissbier",
      type: "Hefeweizen",
      brewery: "Erdinger Weissbräu",
      region: "Bavaria",
      alcoholContent: 5.3,
      isTested: false,
    },
    {
      id: 14,
      name: "Maisel’s Weisse Original",
      type: "Hefeweizen",
      brewery: "Brauerei Gebr. Maisel",
      region: "Bavaria",
      alcoholContent: 5.2,
      isTested: false,
    },
    {
      id: 15,
      name: "Hofbräuhaus Original",
      type: "Helles Lager",
      brewery: "Hofbräuhaus München",
      region: "Bavaria",
      alcoholContent: 5.1,
      isTested: false,
    },
    {
      id: 16,
      name: "Reissdorf Kölsch",
      type: "Kölsch",
      brewery: "Brauerei Heinrich Reissdorf",
      region: "North Rhine-Westphalia",
      alcoholContent: 4.8,
      isTested: false,
    },
    {
      id: 17,
      name: "Schneider Weisse Tap 5 Meine Hopfenweisse",
      type: "Weizenbock",
      brewery: "G. Schneider & Sohn",
      region: "Bavaria",
      alcoholContent: 8.2,
      isTested: false,
    },
    {
      id: 18,
      name: "Ayinger Oktober Fest-Märzen",
      type: "Märzen",
      brewery: "Privatbrauerei Franz Inselkammer KG / Brauerei Aying",
      region: "Bavaria",
      alcoholContent: 5.8,
      isTested: false,
    },
    {
      id: 19,
      name: "Wernesgrüner Pils",
      type: "Pilsner",
      brewery: "Wernesgrüner Brauerei",
      region: "Saxony",
      alcoholContent: 4.9,
      isTested: false,
    },
    {
      id: 20,
      name: "Duckstein Original",
      type: "Amber Ale",
      brewery: "Duckstein Brauerei",
      region: "Hamburg",
      alcoholContent: 4.9,
      isTested: false,
    },
  ];